
function VERDICT(pat_num, opts)
% VERDICT MATLAB function to carry out VERDICT processing (Adam Phipps)
% VERDICT(pat_num, opts)
%
% Adam Phipps, adapted by David Atkinson

arguments
    pat_num % INNOVATE patient number
    opts.modeltype = 'Original VERDICT' % Type of VERDICT model to fit
    opts.schemename = 'Original Full' % Name of imaging scheme
    opts.fittingtechnique = "AMICO" % Fitting framwork to use

    % Solver for AMICO fitting
    opts.solver = 'lsqnonnegTikhonov'

    % Noise parameters used for MLP training
    opts.noisetype = 'Rice'
    opts.sigma0train = 0.05 
    opts.T2train = 10000
    
    % Define folders
    opts.STUDY_path = "" 
    opts.parent_folder = "" 
    opts.schemesfolder = ""
    opts.modelsfolder = ""
    opts.pythonfolder = ""

    % Other calculations
    opts.calcADC = false
    opts.vADCbmax = 1001


end

% Define DICOM folder path
DICOM_path = fullfile( opts.STUDY_path, pat_num, 'scans');
if exist(DICOM_path, "dir")
    disp('')
else
    DICOM_path = fullfile( opts.STUDY_path, pat_num);
end


switch opts.fittingtechnique

    case 'MLP'
        % Define output folder
        output_path = fullfile(opts.parent_folder, 'New VERDICT outputs', ...
            string(opts.modeltype), string(opts.schemename), string(opts.fittingtechnique), ...
            pat_num, string(opts.noisetype), 'T2_', string(opts.T2train), 'sigma_', num2str(opts.sigma0train));

    case 'AMICO'
        % Define output folder
        output_path = fullfile(opts.parent_folder, 'New VERDICT outputs', ...
            string(opts.modeltype), string(opts.schemename), string(opts.fittingtechnique), ...
            pat_num);

end

if ~exist(output_path, "dir")
   mkdir(output_path)
end


%% Apply VERDICT processing

switch opts.modeltype

    case 'Original VERDICT'

        ncompart = 2;
        fitting = 'VERDICT';
        Rs = linspace(0.1, 15.1, 17);


        % Run VERDICT processing code
        [scheme, Y, fIC, fEES, fVASC, R, rmse] = verdict_Adam( ...
            convertStringsToChars(DICOM_path), ...
            convertStringsToChars(output_path), ...
            PatientID = pat_num,...
            parent_folder = opts.parent_folder,...
            schemesfolder = opts.schemesfolder,...
            modelsfolder = opts.modelsfolder,...
            pythonfolder = opts.pythonfolder,...
            modeltype = opts.modeltype,...
            schemename = opts.schemename,...
            fittingtechnique = opts.fittingtechnique,...
            noisetype=opts.noisetype,...
            sigma0train = opts.sigma0train,...
            T2train=opts.T2train,...
            fitting = fitting,...
            ncompart = ncompart, ...
            Rs = Rs,...
            solver = opts.solver,...
            calcADC = opts.calcADC,...
            vADCbmax = opts.vADCbmax);
  


    case 'No VASC VERDICT'

        ncompart = 1;
        fitting = 'VERDICT';
        Rs = linspace(0.1, 15.1, 17);

        % Run VERDICT processing code
        [scheme, Y, fIC, fEES, fVASC, R, rmse] = verdict_Adam( ...
            convertStringsToChars(DICOM_path), ...
            convertStringsToChars(output_path), ...
            PatientID = pat_num,...
            parent_folder = opts.parent_folder,...
            schemesfolder = opts.schemesfolder,...
            modelsfolder = opts.modelsfolder,...
            pythonfolder = opts.pythonfolder,...
            modeltype = opts.modeltype,...
            schemename = opts.schemename,...
            fittingtechnique = opts.fittingtechnique,...
            noisetype=opts.noisetype,...
            sigma0train = opts.sigma0train,...
            T2train=opts.T2train,...
            fitting = fitting,...
            ncompart = ncompart, ...
            solver = opts.solver,...
            calcADC = opts.calcADC,...
            vADCbmax = opts.vADCbmax);


    case 'RDI v1.3'

        ncompart = 1;
        fitting = 'RDI';
        Rs = linspace(0.1, 15.1, 17);

        % Run VERDICT processing code
        [scheme, Y, fIC, fEES, fVASC, R, rmse] = verdict_Adam( ...
            convertStringsToChars(DICOM_path), ...
            convertStringsToChars(output_path), ...
            PatientID = pat_num,...
            parent_folder = opts.parent_folder,...
            schemesfolder = opts.schemesfolder,...
            modelsfolder = opts.modelsfolder,...
            pythonfolder = opts.pythonfolder,...    
            modeltype = opts.modeltype,...
            schemename = opts.schemename,...
            fittingtechnique = opts.fittingtechnique,...
            noisetype=opts.noisetype,...
            sigma0train = opts.sigma0train,...
            T2train=opts.T2train,...
            fitting = fitting,...
            ncompart = ncompart, ...
            solver = opts.solver,...
            calcADC = opts.calcADC,...
            vADCbmax = opts.vADCbmax);

    % case 'RDI v1.4'
    % 
    %     ncompart = 1;
    %     fitting = 'RDI';
    %     Rs = linspace(0.1, 15.1, 17);
    % 
    %     % Run VERDICT processing code
    %     [scheme, Y, fIC, fEES, fVASC, R, rmse] = verdict_Adam( ...
    %         convertStringsToChars(DICOM_path), ...
    %         convertStringsToChars(output_path), ...
    %         PatientID = pat_num,...
    %         parent_folder = opts.parent_folder,...
    %         schemesfolder = opts.schemesfolder,...
    %         modeltype = opts.modeltype,...
    %         schemename = opts.schemename,...
    %         fittingtechnique = opts.fittingtechnique,...
    %         sigma0train = opts.sigma0train,...
    %         fitting = fitting,...
    %         ncompart = ncompart, ...
    %         solver = opts.solver,...
    %         calcADC = opts.calcADC,...
    %         calcT2 = opts.calcT2...
    %         );



end


% Save results
save([convertStringsToChars(output_path) '/fIC.mat'], 'fIC')
save([convertStringsToChars(output_path) '/fEES.mat'], 'fEES')
save([convertStringsToChars(output_path) '/fVASC.mat'], 'fVASC')
save([convertStringsToChars(output_path) '/R.mat'], 'R')
% save([convertStringsToChars(output_path) '/rmse.mat'], 'rmse')

end
